entryPoints:
  web:
    address: :80

api:
  insecure: false
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    # trueにすると同ネットワークのコンテナ全て検知されるので、falseにして、検知するコンテナはcompose側で制御するのが一般的らしい.
