entryPoints:
  web:
    address: :80

api:
  insecure: true # 本番環境ではfalseにする
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    # trueにすると同ネットワークのコンテナ全て検知されるので、falseにして、検知するコンテナはcompose側で制御するのが一般的らしい.

log:
  level: INFO
