http:
  middlewares:
    api-middleware:
      stripPrefix:
        prefixes:
          - "/api"

  routers:
    backend-api:
      rule: "Host(`backend.localhost`)"
      service: backend-api
      middlewares:
        - api-middleware
      entryPoints:
        - web
    dashboard:
      rule: "Host(`traefik.localhost`)"
      service: api@internal # Traefikの内部サービスを使用
      entryPoints:
        - web

  services:
    backend-api:
      loadBalancer:
        servers:
          - url: "http://api:8088" # APIサービスのURL
