http:
  routers:
    backend-api:
      rule: "Host(`api.localhost`)"
      service: backend-api
      entryPoints:
        - web
    dashboard:
      rule: "Host(`traefik.localhost`)"
      service: api@internal # Traefikの内部サービスを使用
      entryPoints:
        - web

  services:
    backend-api:
      loadBalancer:
        servers:
          - url: "http://api:8088" # APIサービスのURL

log:
  level: INFO

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
# TODO: HTTPS化する.
# https://zenn.dev/pitekusu/books/traefik-pitekusu/viewer/https
