FROM rust:1.80-slim-bullseye

WORKDIR /usr/src/app

RUN cargo install cargo-watch

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y \
    curl \
    iputils-ping \
    netcat \
    pkg-config \
    libssl-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

ENV OPENSSL_DIR=/usr/lib/ssl

CMD ["cargo", "watch", "-x", "run"]