name: Rust CI
# バックエンドのRustコードの品質チェックを行うワークフロー
# - コードフォーマットのチェック
# - Clippyによる静的解析
# - セキュリティ監査
# - ビルドテスト（Ubuntu）
# - 未使用依存関係の検出
# - バイナリサイズ分析
# TODO: テストの実行

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "backend/**"
  push:
    branches:
      - develop
      - main
    paths:
      - "backend/**"
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜日の午前0時に実行
  workflow_dispatch: # 手動実行可

# 連続pushの対策
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # 実行中のワークフローをキャンセル

# GitHub Actionsの環境変数設定
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

# 各jobsは独立したワークフローとして実行されるので、各ジョブが同時に開始される
# なお、依存関係に変更がない場合はキャッシュを使うのでビルド高速化
jobs:
  # 共通のキャッシュ設定を定義
  cache-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            backend/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('backend/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

  # フォーマットチェックのジョブ
  format:
    needs: cache-dependencies
    name: Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt --all -- --check

  # 静的解析のジョブ
  lint:
    needs: cache-dependencies
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Clippy check
        run: cargo clippy -- -D warnings

  # セキュリティチェックのジョブ
  security:
    needs: cache-dependencies
    name: Security Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Security audit
        run: cargo audit

  # ビルドチェックのジョブ
  build:
    needs: cache-dependencies
    name: Build
    # developまたはmainブランチへのマージ時のみ実行
    if: github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'main')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build check
        run: cargo build --release

  # 未使用依存関係の検出のジョブ
  unused-dependencies:
    needs: cache-dependencies
    name: Unused Dependencies Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Check if dependencies changed
        id: check-deps
        run: |
          if [ -f ~/.cargo/bin/cargo-udeps ] && [ "$(shasum Cargo.lock)" = "$(cat ~/.cargo/udeps-last-check 2>/dev/null)" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            shasum Cargo.lock > ~/.cargo/udeps-last-check
          fi
      - name: Install cargo-udeps
        if: steps.check-deps.outputs.skip != 'true'
        run: |
          if ! command -v cargo-udeps &> /dev/null; then
            cargo install cargo-udeps --locked
          fi
      - name: Run cargo-udeps
        if: steps.check-deps.outputs.skip != 'true'
        run: cargo +nightly udeps

  # バイナリサイズ分析のジョブ
  binary-size:
    needs: cache-dependencies
    name: Binary Size Analysis
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-bloat
        run: |
          if ! command -v cargo-bloat &> /dev/null; then
            cargo install cargo-bloat --locked
          fi
      - name: Analyze binary size
        run: |
          cargo bloat --release --crates
          cargo bloat --release -n 20
